[package]
name = "integer_list_values"
version = "0.1.0"
authors = ["Johannes Frank <jmfrank63@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
approx = "0.4.0"
